services:
  - type: static_site
    name: laser-game
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: ohio
    autoDeploy: true
    buildCommand: ""
    staticPublishPath: game
